import json
from database import query, count, insert

KNOWLEDGE_POINTS = [
    (1, 'variables', '变量与赋值', 'Variables and assignment in Python', 'basic'),
    (2, 'data_types', '数据类型', 'Basic data types: int, float, str, bool', 'basic'),
    (3, 'operators', '运算符', 'Arithmetic, comparison, and logical operators', 'basic'),
    (4, 'conditionals', '条件判断', 'if/elif/else conditional statements', 'basic'),
    (5, 'loops', '循环结构', 'for and while loops', 'basic'),
    (6, 'strings', '字符串操作', 'String methods and manipulation', 'basic'),
    (7, 'lists', '列表', 'List operations and methods', 'intermediate'),
    (8, 'tuples', '元组', 'Tuple immutability and usage', 'intermediate'),
    (9, 'dicts', '字典', 'Dictionary key-value operations', 'intermediate'),
    (10, 'sets', '集合', 'Set operations and uniqueness', 'intermediate'),
    (11, 'functions', '函数定义', 'Defining and calling functions', 'intermediate'),
    (12, 'parameters', '参数传递', 'Positional, keyword, default, *args, **kwargs', 'intermediate'),
    (13, 'return_values', '返回值', 'Return statements and multiple returns', 'intermediate'),
    (14, 'scope', '作用域', 'Local, global, and nonlocal variable scope', 'intermediate'),
    (15, 'classes', '类定义', 'Class definition, __init__, self', 'advanced'),
    (16, 'inheritance', '继承与多态', 'Class inheritance and polymorphism', 'advanced'),
    (17, 'modules', '模块导入', 'import, from...import, packages', 'advanced'),
    (18, 'exceptions', '异常处理', 'try/except/finally/raise', 'advanced'),
    (19, 'file_io', '文件操作', 'Reading and writing files', 'advanced'),
    (20, 'comprehensions', '推导式', 'List, dict, and set comprehensions', 'intermediate'),
]

KNOWLEDGE_EDGES = [
    (1, 2), (2, 3), (3, 4), (4, 5), (2, 6), (2, 7), (7, 8), (7, 9),
    (7, 10), (6, 7), (5, 11), (11, 12), (11, 13), (11, 14),
    (11, 15), (15, 16), (11, 17), (11, 18), (17, 18), (6, 19),
    (7, 20), (9, 20),
]

SINGLE_CHOICE_QUESTIONS = [


    ("Python中用于定义变量的关键字是？",
     '["A. var", "B. let", "C. 不需要关键字，直接赋值", "D. def"]', 'C', 1, [1]),
    ("以下哪个是Python中的整数类型？",
     '["A. float", "B. int", "C. string", "D. boolean"]', 'B', 1, [2]),
    ("Python中字符串的定义方式是？",
     '["A. 单引号或双引号", "B. 只能单引号", "C. 只能双引号", "D. 用尖括号"]', 'A', 1, [6]),
    ("以下哪个运算符用于取余？",
     '["A. /", "B. //", "C. %", "D. **"]', 'C', 1, [3]),
    ("Python中注释的正确写法是？",
     '["A. // 注释内容", "B. <!-- 注释内容 -->", "C. # 注释内容", "D. /* 注释内容 */"]', 'C', 1, [1]),
    ("len()函数的作用是什么？",
     '["A. 获取数字的长度", "B. 获取序列的长度", "C. 获取文件长度", "D. 获取布尔值"]', 'B', 1, [2, 6]),
    ("下列哪个表达式的结果为True？",
     '["A. 3 > 5", "B. 2 == 3", "C. 1 < 2", "D. 0 > 1"]', 'C', 1, [3]),
    ("Python中布尔类型的取值包括？",
     '["A. 0和1", "B. true和false", "C. True和False", "D. Yes和No"]', 'C', 1, [2]),
    ("以下哪个是正确的变量命名？",
     '["A. 2name", "B. my-name", "C. _name", "D. class"]', 'C', 2, [1]),
    ("list = [1,2,3]; list[0]的结果是？",
     '["A. 0", "B. 1", "C. 2", "D. 3"]', 'B', 2, [7]),
    ("Python中如何向列表添加元素？",
     '["A. list.add(4)", "B. list.append(4)", "C. list.insert(4)", "D. list.push(4)"]', 'B', 2, [7]),
    ("for i in range(3): print(i) 输出结果是？",
     '["A. 1 2 3", "B. 0 1 2 3", "C. 0 1 2", "D. 1 2"]', 'C', 2, [5]),
    ("以下哪个是Python中字典的定义方式？",
     '["A. {key: value}", "B. [key: value]", "C. (key: value)", "D. <key: value>"]', 'A', 2, [9]),
    ("函数定义使用哪个关键字？",
     '["A. function", "B. def", "C. fn", "D. func"]', 'B', 2, [11]),
    ("a = [1,2,3]; a[1:]的结果是？",
     '["A. [1]", "B. [2,3]", "C. [1,2]", "D. [3]"]', 'B', 2, [7]),
    ("{1,2,3} & {2,3,4} 的结果是？",
     '["A. {1,2,3,4}", "B. {2,3}", "C. {1,4}", "D. {1}"]', 'B', 3, [10]),
    ("以下哪个不是Python内置函数？",
     '["A. print()", "B. len()", "C. push()", "D. type()"]', 'C', 2, [11]),
    ("字典的键必须是什么类型？",
     '["A. 只能是字符串", "B. 只能是数字", "C. 不可变类型", "D. 任意类型"]', 'C', 3, [9]),
    ("Python中None表示什么？",
     '["A. 数字0", "B. 空字符串", "C. 空值/无", "D. 布尔False"]', 'C', 2, [2]),
    ("def f(a,b=2): 中b是什么参数？",
     '["A. 位置参数", "B. 默认参数", "C. 关键字参数", "D. 可变参数"]', 'B', 2, [12]),
    ("*args在函数定义中表示？",
     '["A. 关键字参数", "B. 默认参数", "C. 可变位置参数", "D. 可变关键字参数"]', 'C', 3, [12]),
    ("类中的self参数代表什么？",
     '["A. 类本身", "B. 实例本身", "C. 父类", "D. 模块"]', 'B', 3, [15]),
    ("__init__方法的作用是？",
     '["A. 初始化类变量", "B. 初始化实例属性", "C. 删除实例", "D. 调用父类"]', 'B', 3, [15]),
    ("以下哪种导入方式是正确的？",
     '["A. import math.py", "B. from math import sqrt", "C. include math", "D. using math"]', 'B', 3, [17]),
    ("try...except的作用是？",
     '["A. 循环控制", "B. 异常捕获", "C. 条件判断", "D. 函数定义"]', 'B', 3, [18]),
    ("open()函数的默认模式是？",
     '["A. w", "B. a", "C. r", "D. x"]', 'C', 3, [19]),
    ("列表推导式 [x*2 for x in range(3)] 的结果是？",
     '["A. [0,1,2]", "B. [0,2,4]", "C. [2,4,6]", "D. [1,2,3]"]', 'B', 3, [20]),
    ("下列哪个语句可以终止循环？",
     '["A. continue", "B. break", "C. pass", "D. stop"]', 'B', 2, [5]),
    ("a = 5; b = a; a = 3; print(b) 输出？",
     '["A. 3", "B. 5", "C. 0", "D. None"]', 'B', 3, [1, 2]),
    ("以下哪个是Python中的元组？",
     '["A. [1,2,3]", "B. {1,2,3}", "C. (1,2,3)", "D. <1,2,3>"]', 'C', 2, [8]),
    ("with语句通常用于什么场景？",
     '["A. 循环", "B. 文件操作/资源管理", "C. 异常处理", "D. 函数定义"]', 'B', 3, [19, 18]),
    ("继承时调用父类方法使用？",
     '["A. self.parent.method()", "B. super().method()", "C. parent.method()", "D. base.method()"]', 'B', 4, [16]),
    ("[1,2,3] + [4,5] 的结果是？",
     '["A. [5,7,3]", "B. [1,2,3,4,5]", "C. [1,2,3,[4,5]]", "D. 报错"]', 'B', 2, [7]),
    ("以下哪个方法可以从列表中删除元素？",
     '["A. list.delete(x)", "B. list.remove(x)", "C. list.erase(x)", "D. list.del(x)"]', 'B', 2, [7]),
    ("global关键字的作用是？",
     '["A. 定义全局变量", "B. 在函数内声明使用全局变量", "C. 导入全局模块", "D. 创建全局函数"]', 'B', 4, [14]),
    ("非局部变量声明使用哪个关键字？",
     '["A. global", "B. nonlocal", "C. outer", "D. external"]', 'B', 4, [14]),
    ("isinstance(5, int) 返回什么？",
     '["A. 5", "B. True", "C. False", "D. int"]', 'B', 3, [2, 18]),
    ("raise关键字用于？",
     '["A. 捕获异常", "B. 抛出异常", "C. 忽略异常", "D. 处理异常"]', 'B', 4, [18]),
    ("Python中set()函数的作用是？",
     '["A. 设置变量值", "B. 创建集合", "C. 设置属性", "D. 设置环境变量"]', 'B', 2, [10]),
    ("f'{name} is {age}' 这种字符串写法叫做？",
     '["A. 格式化字符串", "B. f-string", "C. 模板字符串", "D. 正则表达式"]', 'B', 3, [6]),
]

MULTI_CHOICE_QUESTIONS = [
    ("以下哪些是Python的合法数据类型？（多选）",
     '["A. int", "B. float", "C. str", "D. char", "E. bool", "F. list"]',
     'A,B,C,E,F', 1, [2]),
    ("以下哪些是有序序列？（多选）",
     '["A. 列表", "B. 集合", "C. 字符串", "D. 元组", "E. 字典"]',
     'A,C,D', 2, [6, 7, 8]),
    ("以下哪些是可变类型？（多选）",
     '["A. int", "B. list", "C. tuple", "D. dict", "E. set", "F. str"]',
     'B,D,E', 3, [2, 7, 8, 9, 10]),
    ("以下哪些操作会修改原列表？（多选）",
     '["A. list.append(4)", "B. list + [4]", "C. list.sort()", "D. list * 2", "E. list.pop()", "F. sorted(list)"]',
     'A,C,E', 3, [7]),
    ("以下关于函数的说法正确的有？（多选）",
     '["A. 可以有默认参数", "B. 可以返回多个值", "C. 可以不写return", "D. Python不支持递归", "E. 可以嵌套定义函数", "F. 参数可以传列表"]',
     'A,B,C,E,F', 3, [11, 12, 13]),
    ("以下关于类的说法正确的有？（多选）",
     '["A. __init__是构造方法", "B. self代表实例本身", "C. 可以多重继承", "D. 类属性所有实例共享", "E. 子类不能重写父类方法", "F. 可以定义静态方法"]',
     'A,B,C,D,F', 4, [15, 16]),
    ("以下哪些会导致异常？（多选）",
     '["A. 10/0", "B. int(abc)", "C. [1,2,3][5]", "D. 1+2", "E. open(noexist.txt, r)", "F. len(123)"]',
     'A,B,C,E,F', 3, [18]),
    ("以下关于模块的说法正确的有？（多选）",
     '["A. 用import导入", "B. 可以用as取别名", "C. 只能导入整个模块", "D. 自定义模块就是一个.py文件", "E. __name__可以判断是否主程序"]',
     'A,B,D,E', 3, [17]),
    ("以下哪些语法在Python中合法？（多选）",
     '["A. a,b = 1,2", "B. x = y = 1", "C. a += 1", "D. a++", "E. x,y = y,x", "F. 1 < x < 5"]',
     'A,B,C,E,F', 3, [1, 3]),
    ("以下关于文件操作正确的有？（多选）",
     '["A. 打开模式r表示读", "B. w表示写且覆盖", "C. a表示追加", "D. b表示二进制模式", "E. 文件使用后应调用close()", "F. with自动关闭文件"]',
     'A,B,C,D,E,F', 2, [19]),
]

TRUE_FALSE_QUESTIONS = [
    ("Python是一种解释型语言。", "T", 1, [1]),
    ("Python中的变量必须先声明类型才能使用。", "F", 1, [1, 2]),
    ("Python使用缩进来表示代码块。", "T", 1, [1]),
    ("Python中单引号和双引号定义的字符串是等价的。", "T", 1, [6]),
    ("3/2的结果是1。", "F", 1, [3]),
    ("Python中的索引从0开始。", "T", 1, [7]),
    ("列表和元组的区别在于列表可变、元组不可变。", "T", 2, [7, 8]),
    ("集合中的元素可以重复。", "F", 2, [10]),
    ("字典的值可以是任意类型。", "T", 2, [9]),
    ("函数的return语句可以省略。", "T", 2, [11, 13]),
    ("Python中函数可以嵌套定义。", "T", 3, [11]),
    ("*args用于接收关键字参数。", "F", 3, [12]),
    ("类的__init__方法在创建实例时自动调用。", "T", 3, [15]),
    ("Python支持多重继承。", "T", 4, [16]),
    ("子类可以重写父类的方法。", "T", 3, [16]),
    ("import只能导入标准库模块。", "F", 2, [17]),
    ("try语句必须有except子句。", "F", 3, [18]),
    ("finally子句中的代码无论是否异常都会执行。", "T", 3, [18]),
    ("with open() as f: 可以自动关闭文件。", "T", 3, [19]),
    ("Python使用&&和||作为逻辑运算符。", "F", 1, [3]),
    ("在函数内部修改全局可变对象不需要global声明。", "T", 4, [14, 7]),
    ("列表推导式可以包含条件判断。", "T", 3, [20]),
    ("匿名函数使用lambda关键字定义。", "T", 3, [11]),
    ("字典的键必须是不可变类型。", "T", 3, [9]),
    ("任何类都隐式继承自object。", "T", 4, [15, 16]),
    ("is运算符比较的是值是否相等。", "F", 3, [3]),
    ("global关键字用于在局部作用域内修改全局变量。", "T", 3, [14]),
    ("enumerate()函数可以同时获取索引和值。", "T", 3, [5, 7]),
    ("zip()函数可以将多个序列配对成元组。", "T", 3, [11]),
    ("round(2.675, 2) 的结果是 2.68。", "T", 4, [3]),
    ("%s可以用于格式化整数。", "F", 3, [6]),
    ("文件以'w+'模式打开时，既有读权限也有写权限。", "T", 3, [19]),
    ("递归函数必须有终止条件。", "T", 4, [11]),
    ("import mod as m 中的as用于重命名模块。", "T", 2, [17]),
    ("__name__ == '__main__' 可以判断脚本是否被直接运行。", "T", 3, [17]),
    ("Python中的空字符串等于None。", "F", 2, [2, 6]),
    ("元组可以通过索引访问元素。", "T", 2, [8]),
    ("集合支持下标索引访问。", "F", 2, [10]),
    ("函数默认参数可以使用可变对象而不会有问题。", "F", 4, [12]),
    ("多个except子句可以捕获不同类型的异常。", "T", 3, [18]),
    ("列表的sort()方法返回排序后的新列表。", "F", 3, [7]),
    ("Python支持递归函数。", "T", 3, [11]),
    ("Python中字符串是不可变的。", "T", 2, [6]),
    ("break语句用于跳过本次循环剩余代码。", "F", 2, [5]),
    ("在try...except...finally中，finally总是在return之前执行。", "T", 4, [18]),
    ("一个Python文件中可以定义多个类。", "T", 3, [15]),
    ("字典的get()方法在键不存在时会抛出异常。", "F", 3, [9]),
    ("*运算符可以用于解包列表。", "T", 3, [7, 12]),
    ("for循环可以搭配else子句。", "T", 4, [5]),
    ("raise可以不带参数使用。", "T", 3, [18]),
]

FILL_BLANK_QUESTIONS = [
    ("Python中用于屏幕输出的内置函数是____。", "print", ["print()", "print", "Print"],
     ["PRINT", "Print", "print", "print()", "println", "echo", "system.out.print", "console.log"], 1, [1]),
    ("获取列表长度的函数是____。", "len", ["len()", "len", "length"],
     ["LEN", "len", "len()", "length", "size", "count", "sizeof", "getlength"], 1, [7]),
    ("Python中用于接收用户输入的函数是____。", "input", ["input()", "Input", "get_input"],
     ["INPUT", "input", "input()", "getinput", "readline", "scanf"], 1, [1]),
    ("Python中表示空值的常量是____。", "None", ["none", "NONE", "null"],
     ["NONE", "none", "None", "null", "NULL", "nil", "nothing"], 1, [2]),
    ("将字符串转为整数的函数是____。", "int", ["int()", "integer", "Int"],
     ["INT", "int", "int()", "integer", "toint", "parseint", "converttoint"], 1, [6]),
    ("用于循环遍历序列的关键字是____。", "for", ["For", "FOR", "foreach"],
     ["FOR", "for", "For", "foreach", "loop", "while", "each"], 1, [5]),
    ("定义类的关键字是____。", "class", ["Class", "CLASS"],
     ["CLASS", "class", "Class", "object", "struct", "type"], 2, [15]),
    ("导入模块时给模块起别名的关键字是____。", "as", ["As", "AS"],
     ["AS", "as", "As", "alias", "named", "rename"], 2, [17]),
    ("判断一个值是否在列表中的关键字是____。", "in", ["In", "IN"],
     ["IN", "in", "In", "contains", "has", "include", "exist"], 2, [7, 3]),
    ("在函数内声明使用全局变量的关键字是____。", "global", ["Global", "GLOBAL"],
     ["GLOBAL", "global", "Global", "outer", "extern", "public"], 3, [14]),
    ("Python的交互式解释器在命令行输入____启动。", "python", ["Python", "PYTHON"],
     ["PYTHON", "python", "Python", "py", "python3", "python.exe", "ipython"], 1, [1]),
    ("生成一个从0到n-1整数序列的函数是____。", "range", ["Range", "RANGE", "range()"],
     ["RANGE", "range", "Range", "range()", "seq", "sequence", "arange", "enumerate"], 2, [5]),
    ("用于获取对象类型的函数是____。", "type", ["Type", "TYPE", "type()"],
     ["TYPE", "type", "Type", "type()", "typeof", "gettype", "class", "isinstance"], 2, [2]),
    ("返回列表中最大值的函数是____。", "max", ["Max", "MAX", "max()"],
     ["MAX", "max", "Mac", "max()", "maximum", "largest", "biggest", "top"], 2, [7]),
    ("用于条件判断的关键字是____。", "if", ["If", "IF"],
     ["IF", "if", "If", "when", "case", "switch", "condition"], 1, [4]),
    ("字典中通过____访问对应的值。", "键", ["key", "键值", "索引"],
     ["键", "key", "Key", "KEY", "键值", "keys", "索引", "下标", "主键", "属性"], 2, [9]),
    ("________是一种允许在一条语句中嵌入表达式的字符串字面量，以前缀f或F开头。", "f-string", ["f-string", "fstring", "F-string", "格式化字符串字面量"],
     ["F-STRING", "f-string", "fstring", "F-string", "f string", "format string literal", "formatted string", "格式化字符串", "f_str", "f_string", "格式化字符串字面量"], 3, [6]),
    ("通过________装饰器可以将一个函数转变为静态方法。", "staticmethod", ["staticmethod", "static_method", "静态方法"],
     ["STATICMETHOD", "staticmethod", "static_method", "静态方法", "StaticMethod", "@staticmethod", "decorator"], 4, [15]),
    ("________是Python中用于处理迭代器的内置函数，返回由索引和值组成的枚举对象。", "enumerate", ["enumerate()", "Enumerate", "枚举"],
     ["ENUMERATE", "enumerate", "Enumerate", "enumerate()", "enum", "枚举", "each with index", "for index value", "range(len("], 3, [5, 7]),
    ("________运算符用于测试两个变量是否指向同一对象（而非值相等）。", "is", ["Is", "IS"],
     ["IS", "is", "Is", "same", "identical", "equal", "指针", "引用"], 3, [3]),
    ("在Python中，使用________关键字可以在循环中跳过当前迭代并继续下一次循环。", "continue", ["Continue", "CONTINUE"],
     ["CONTINUE", "continue", "Continue", "skip", "next", "pass", "jump", "resume"], 2, [5]),
    ("________语句用于在条件为假时执行另一段代码块，与if配套使用。", "else", ["Else", "ELSE"],
     ["ELSE", "else", "Else", "otherwise", "elif", "default", "then"], 1, [4]),
    ("将多个字符串合并成一个字符串的操作称为字符串________。", "拼接", ["连接", "合并", "concatenation", "concat"],
     ["拼接", "连接", "合并", "concatenation", "concat", "组合", "相加", "join", "串接", "衔接", "concatentation", "并置"], 2, [6]),
    ("________是Python的代码组织单元，一个.py文件就是一个。", "模块", ["module", "Module", "库"],
     ["模块", "module", "Module", "library", "库", "包", "组件", "model", "文件"], 2, [17]),
    ("Python中实现多态的关键机制被称为________类型。", "鸭子", ["duck", "Duck", "动态"],
     ["鸭子", "duck", "Duck", "duck typing", "动态", "dynamic", "运行时", "多态", "接口", "抽象"], 4, [16]),
    ("用于将一个列表中的所有元素连接成一个字符串的方法是________。", "join", ["Join", "JOIN", "join()", "连接"],
     ["JOIN", "join", "Join", "join()", "concat", "连接", "combine", "merge"], 3, [6, 7]),
    ("在Python中，________是一种map-like的数据结构，通过大括号{}定义，以键值对形式存储。", "字典", ["dictionary", "dict", "Dictionary", "映射"],
     ["字典", "dictionary", "dict", "Dictionary", "Dict", "映射", "map", "maping", "hashmap", "关联数组", "哈希表", "键值对"], 2, [9]),
    ("Python中用于终止程序运行的函数是________。", "exit", ["exit()", "Exit", "sys.exit", "quit"],
     ["EXIT", "exit", "Exit", "exit()", "quit", "quit()", "sys.exit", "stop", "terminate", "end"], 3, [18]),
    ("函数定义时，________参数在函数调用时如果没有提供实参会使用预设值。", "默认", ["default", "缺省", "可选"],
     ["默认", "default", "缺省", "optional", "预设", "缺省值", "默认值", "default value", "optional argument", "预备", "预置"], 2, [12]),
    ("________是Python中列表对象的一种方法，在指定位置插入元素。", "insert", ["Insert", "INSERT", "insert()"],
     ["INSERT", "insert", "Insert", "insert()", "add", "place", "put", "append", "extend"], 2, [7]),
]

PROGRAMMING_QUESTIONS = [
    {
        'title': '凯撒密码加密解密',
        'desc': '编写函数 caesar_encrypt(text, shift) 实现凯撒密码加密：字母循环右移 shift 位，保留大小写，非字母字符不变。再编写函数 caesar_decrypt(text, shift) 解密（调用 encrypt 反向移动即可）。',
        'func': 'caesar_encrypt',
        'test_cases': [
            {'input': '', 'call': 'print(caesar_encrypt("Hello, World!", 3))', 'expected': 'Khoor, Zruog!'},
            {'input': '', 'call': 'print(caesar_encrypt("xyz", 3))', 'expected': 'abc'},
            {'input': '', 'call': 'print(caesar_encrypt("123!@#", 5))', 'expected': '123!@#'},
            {'input': '', 'call': 'print(caesar_decrypt("Khoor", 3))', 'expected': 'Hello'},
            {'input': '', 'call': 'print(caesar_decrypt(caesar_encrypt("Test", 7), 7))', 'expected': 'Test'},
        ],
        'reference': 'def caesar_encrypt(text, shift):\n    result = []\n    shift = shift % 26\n    for ch in text:\n        if \'A\' <= ch <= \'Z\':\n            base = ord(\'A\')\n            result.append(chr((ord(ch) - base + shift) % 26 + base))\n        elif \'a\' <= ch <= \'z\':\n            base = ord(\'a\')\n            result.append(chr((ord(ch) - base + shift) % 26 + base))\n        else:\n            result.append(ch)\n    return \'\'.join(result)\n\ndef caesar_decrypt(text, shift):\n    return caesar_encrypt(text, -shift)\n',
        'ai_template': 'def caesar_encrypt(text: str, shift: int) -> str:\n    """Encrypt a string using the Caesar cipher.\n    \n    Each letter in the plaintext is shifted by a fixed number of positions\n    down the alphabet, wrapping around at the ends. Non-alphabetic\n    characters are preserved as-is.\n    \n    Args:\n        text: The plaintext string to encrypt.\n        shift: Number of positions to shift (can be any integer).\n    \n    Returns:\n        The encrypted ciphertext string.\n    """\n    import string\n    result = []\n    effective_shift = shift % 26\n    for character in text:\n        if character.isupper():\n            shifted = chr((ord(character) - ord(\'A\') + effective_shift) % 26 + ord(\'A\'))\n            result.append(shifted)\n        elif character.islower():\n            shifted = chr((ord(character) - ord(\'a\') + effective_shift) % 26 + ord(\'a\'))\n            result.append(shifted)\n        else:\n            result.append(character)\n    return \'\'.join(result)\n\ndef caesar_decrypt(text: str, shift: int) -> str:\n    """Decrypt a Caesar-cipher-encrypted string.\n    \n    Args:\n        text: The ciphertext to decrypt.\n        shift: The shift value used during encryption.\n    \n    Returns:\n        The decrypted plaintext.\n    """\n    return caesar_encrypt(text, -shift)\n',
        'code_template': 'def caesar_encrypt(text, shift):\n    # Write your code here\n    pass\n\ndef caesar_decrypt(text, shift):\n    # Write your code here\n    pass\n',
        'difficulty': 3, 'kp': [6, 5, 4, 11],
    },
    {
        'title': '成绩统计分析',
        'desc': '编写函数 analyze_scores(scores)，接收整数列表（0-100的分数），返回统计字典，包含: count(人数), avg(平均分保留1位小数), max(最高分), min(最低分), pass_count(>=60及格人数), pass_rate(及格率百分数保留1位), grade_dist(五档分布: A>=90, B>=80, C>=70, D>=60, F<60)。空列表返回各项为0的字典。',
        'func': 'analyze_scores',
        'test_cases': [
            {'input': '', 'call': 'print(analyze_scores([85, 92, 78, 60, 45]))', 'expected': "{'count': 5, 'avg': 72.0, 'max': 92, 'min': 45, 'pass_count': 4, 'pass_rate': 80.0, 'grade_dist': {'A': 1, 'B': 1, 'C': 1, 'D': 1, 'F': 1}}"},
            {'input': '', 'call': 'print(analyze_scores([]))', 'expected': "{'count': 0, 'avg': 0.0, 'max': 0, 'min': 0, 'pass_count': 0, 'pass_rate': 0.0, 'grade_dist': {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'F': 0}}"},
            {'input': '', 'call': 'print(analyze_scores([100, 95, 90, 85, 80]))', 'expected': "{'count': 5, 'avg': 90.0, 'max': 100, 'min': 80, 'pass_count': 5, 'pass_rate': 100.0, 'grade_dist': {'A': 3, 'B': 2, 'C': 0, 'D': 0, 'F': 0}}"},
        ],
        'reference': 'def analyze_scores(scores):\n    if not scores:\n        return {\'count\': 0, \'avg\': 0.0, \'max\': 0, \'min\': 0, \'pass_count\': 0, \'pass_rate\': 0.0, \'grade_dist\': {\'A\': 0, \'B\': 0, \'C\': 0, \'D\': 0, \'F\': 0}}\n    count = len(scores)\n    total = sum(scores)\n    avg = round(total / count, 1)\n    max_score = max(scores)\n    min_score = min(scores)\n    pass_count = sum(1 for s in scores if s >= 60)\n    pass_rate = round(pass_count / count * 100, 1)\n    grade_dist = {\'A\': 0, \'B\': 0, \'C\': 0, \'D\': 0, \'F\': 0}\n    for s in scores:\n        if s >= 90:\n            grade_dist[\'A\'] += 1\n        elif s >= 80:\n            grade_dist[\'B\'] += 1\n        elif s >= 70:\n            grade_dist[\'C\'] += 1\n        elif s >= 60:\n            grade_dist[\'D\'] += 1\n        else:\n            grade_dist[\'F\'] += 1\n    return {\'count\': count, \'avg\': avg, \'max\': max_score, \'min\': min_score, \'pass_count\': pass_count, \'pass_rate\': pass_rate, \'grade_dist\': grade_dist}\n',
        'ai_template': 'from typing import List, Dict, Union\n\ndef analyze_scores(scores: List[int]) -> Dict[str, Union[int, float, Dict[str, int]]]:\n    """Analyze a list of student scores and return comprehensive statistics.\n    \n    Computes basic statistics (count, average, min, max), pass/fail metrics,\n    and a grade distribution across five letter-grade bands.\n    \n    Args:\n        scores: A list of integer scores in the range [0, 100].\n    \n    Returns:\n        A dictionary containing count, avg, max, min, pass_count,\n        pass_rate, and grade_dist (A/B/C/D/F counts).\n    \n    Raises:\n        ValueError: If any score is outside the valid range [0, 100].\n    """\n    # Validate input\n    for score in scores:\n        if not (0 <= score <= 100):\n            raise ValueError(f"Invalid score: {score}. Must be 0-100.")\n    \n    # Handle empty input\n    if not scores:\n        return {\n            \'count\': 0, \'avg\': 0.0, \'max\': 0, \'min\': 0,\n            \'pass_count\': 0, \'pass_rate\': 0.0,\n            \'grade_dist\': {\'A\': 0, \'B\': 0, \'C\': 0, \'D\': 0, \'F\': 0}\n        }\n    \n    # Compute statistics\n    number_of_students = len(scores)\n    total_score = sum(scores)\n    average_score = round(total_score / number_of_students, 1)\n    maximum_score = max(scores)\n    minimum_score = min(scores)\n    passing_students = sum(1 for score in scores if score >= 60)\n    passing_percentage = round(passing_students / number_of_students * 100, 1)\n    \n    # Grade distribution\n    distribution = {\'A\': 0, \'B\': 0, \'C\': 0, \'D\': 0, \'F\': 0}\n    for individual_score in scores:\n        if individual_score >= 90:\n            distribution[\'A\'] += 1\n        elif individual_score >= 80:\n            distribution[\'B\'] += 1\n        elif individual_score >= 70:\n            distribution[\'C\'] += 1\n        elif individual_score >= 60:\n            distribution[\'D\'] += 1\n        else:\n            distribution[\'F\'] += 1\n    \n    return {\n        \'count\': number_of_students,\n        \'avg\': average_score,\n        \'max\': maximum_score,\n        \'min\': minimum_score,\n        \'pass_count\': passing_students,\n        \'pass_rate\': passing_percentage,\n        \'grade_dist\': distribution\n    }\n',
        'code_template': 'def analyze_scores(scores):\n    # Write your code here\n    pass\n',
        'difficulty': 2, 'kp': [5, 7, 11, 9, 4],
    },
    {
        'title': '计算阶乘',
        'desc': '编写函数 factorial(n)，接收非负整数n，返回n的阶乘(n!)。0的阶乘为1。',
        'func': 'factorial',
        'test_cases': [
            {'input': '', 'call': 'print(factorial(5))', 'expected': '120'},
            {'input': '', 'call': 'print(factorial(0))', 'expected': '1'},
            {'input': '', 'call': 'print(factorial(3))', 'expected': '6'},
        ],
        'reference': 'def factorial(n):\n    result = 1\n    for i in range(1, n + 1):\n        result *= i\n    return result\n',
        'ai_template': 'def factorial(n):\n    """Calculate the factorial of n using iteration.\n    \n    Args:\n        n: A non-negative integer\n    \n    Returns:\n        The factorial of n (n!)\n    \n    Raises:\n        ValueError: If n is negative\n    """\n    if n < 0:\n        raise ValueError("n must be non-negative")\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n',
        'code_template': 'def factorial(n):\n    pass\n',
        'difficulty': 2, 'kp': [5, 11, 13],
    },
    {
        'title': '列表元素求和',
        'desc': '编写函数 list_sum(lst)，接收一个数字列表，返回所有元素之和。不得使用内置sum()函数。',
        'func': 'list_sum',
        'test_cases': [
            {'input': '', 'call': 'print(list_sum([1, 2, 3, 4, 5]))', 'expected': '15'},
            {'input': '', 'call': 'print(list_sum([]))', 'expected': '0'},
            {'input': '', 'call': 'print(list_sum([-1, 1]))', 'expected': '0'},
        ],
        'reference': 'def list_sum(lst):\n    total = 0\n    for x in lst:\n        total += x\n    return total\n',
        'ai_template': 'def list_sum(lst):\n    """Calculate the sum of all elements in a list.\n    \n    Args:\n        lst: A list of numeric values\n    \n    Returns:\n        The total sum of all elements\n    """\n    accumulator = 0\n    for element in lst:\n        accumulator += element\n    return accumulator\n',
        'code_template': 'def list_sum(lst):\n    pass\n',
        'difficulty': 1, 'kp': [5, 7, 11],
    },
    {
        'title': '字符串反转',
        'desc': '编写函数 reverse_string(s)，接收一个字符串，返回其反转后的字符串。',
        'func': 'reverse_string',
        'test_cases': [
            {'input': '', 'call': 'print(reverse_string("hello"))', 'expected': 'olleh'},
            {'input': '', 'call': 'print(reverse_string(""))', 'expected': ''},
            {'input': '', 'call': 'print(reverse_string("a"))', 'expected': 'a'},
        ],
        'reference': 'def reverse_string(s):\n    return s[::-1]\n',
        'ai_template': 'def reverse_string(s):\n    """Reverse a given string.\n    \n    Args:\n        s: The input string to be reversed\n    \n    Returns:\n        The reversed string\n    """\n    reversed_str = ""\n    for char in s:\n        reversed_str = char + reversed_str\n    return reversed_str\n',
        'code_template': 'def reverse_string(s):\n    pass\n',
        'difficulty': 2, 'kp': [6, 5, 11],
    },
    {
        'title': '查找最大值',
        'desc': '编写函数 find_max(lst)，接收非空数字列表，返回最大值。不得使用max()函数。',
        'func': 'find_max',
        'test_cases': [
            {'input': '', 'call': 'print(find_max([1, 5, 3, 9, 2]))', 'expected': '9'},
            {'input': '', 'call': 'print(find_max([42]))', 'expected': '42'},
            {'input': '', 'call': 'print(find_max([-5, -1, -10]))', 'expected': '-1'},
        ],
        'reference': 'def find_max(lst):\n    max_val = lst[0]\n    for x in lst[1:]:\n        if x > max_val:\n            max_val = x\n    return max_val\n',
        'ai_template': 'def find_max(lst):\n    """Find the maximum value in a list.\n    \n    Args:\n        lst: A non-empty list of comparable elements\n    \n    Returns:\n        The maximum element in the list\n    """\n    current_max = lst[0]\n    for i in range(1, len(lst)):\n        if lst[i] > current_max:\n            current_max = lst[i]\n    return current_max\n',
        'code_template': 'def find_max(lst):\n    pass\n',
        'difficulty': 2, 'kp': [5, 7, 11],
    },
    {
        'title': '判断素数',
        'desc': '编写函数 is_prime(n)，接收大于1的整数，判断是否为素数。素数：只能被1和自身整除。',
        'func': 'is_prime',
        'test_cases': [
            {'input': '', 'call': 'print(is_prime(7))', 'expected': 'True'},
            {'input': '', 'call': 'print(is_prime(10))', 'expected': 'False'},
            {'input': '', 'call': 'print(is_prime(2))', 'expected': 'True'},
        ],
        'reference': 'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n',
        'ai_template': 'def is_prime(n):\n    """Check if a number is prime.\n    \n    Args:\n        n: An integer greater than 1\n    \n    Returns:\n        bool: True if n is prime, False otherwise\n    """\n    if n <= 1:\n        return False\n    import math\n    for divisor in range(2, int(math.sqrt(n)) + 1):\n        if n % divisor == 0:\n            return False\n    return True\n',
        'code_template': 'def is_prime(n):\n    pass\n',
        'difficulty': 3, 'kp': [5, 4, 11, 17],
    },
    {
        'title': '斐波那契数列',
        'desc': '编写函数 fibonacci(n)，返回斐波那契数列的第n项（从0开始：F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)）。',
        'func': 'fibonacci',
        'test_cases': [
            {'input': '', 'call': 'print(fibonacci(0))', 'expected': '0'},
            {'input': '', 'call': 'print(fibonacci(5))', 'expected': '5'},
            {'input': '', 'call': 'print(fibonacci(10))', 'expected': '55'},
        ],
        'reference': 'def fibonacci(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    return b\n',
        'ai_template': 'def fibonacci(n):\n    """Compute the nth Fibonacci number using dynamic programming.\n    \n    Args:\n        n: The index (0-indexed)\n    \n    Returns:\n        The nth Fibonacci number\n    """\n    memo = {0: 0, 1: 1}\n    def dp(k):\n        if k not in memo:\n            memo[k] = dp(k - 1) + dp(k - 2)\n        return memo[k]\n    return dp(n)\n',
        'code_template': 'def fibonacci(n):\n    pass\n',
        'difficulty': 3, 'kp': [5, 11, 13, 9],
    },
    {
        'title': '统计字符频率',
        'desc': '编写函数 char_count(s)，接收字符串，返回字典，键为字符，值为出现次数。',
        'func': 'char_count',
        'test_cases': [
            {'input': '', 'call': 'print(char_count("hello"))', 'expected': "{'h':1,'e':1,'l':2,'o':1}"},
            {'input': '', 'call': 'print(char_count(""))', 'expected': '{}'},
            {'input': '', 'call': 'print(char_count("aaa"))', 'expected': "{'a':3}"},
        ],
        'reference': 'def char_count(s):\n    result = {}\n    for c in s:\n        result[c] = result.get(c, 0) + 1\n    return result\n',
        'ai_template': 'def char_count(s):\n    """Count the frequency of each character in a string.\n    \n    Args:\n        s: Input string\n    \n    Returns:\n        dict: Character frequency dictionary\n    """\n    from collections import Counter\n    return dict(Counter(s))\n',
        'code_template': 'def char_count(s):\n    pass\n',
        'difficulty': 2, 'kp': [6, 9, 5, 11],
    },
    {
        'title': '列表去重',
        'desc': '编写函数 unique(lst)，接收列表，返回去除重复元素的新列表，保持原顺序。',
        'func': 'unique',
        'test_cases': [
            {'input': '', 'call': 'print(unique([1,2,2,3,3,3]))', 'expected': '[1,2,3]'},
            {'input': '', 'call': 'print(unique([1,1,1]))', 'expected': '[1]'},
            {'input': '', 'call': 'print(unique([]))', 'expected': '[]'},
        ],
        'reference': 'def unique(lst):\n    seen = set()\n    result = []\n    for x in lst:\n        if x not in seen:\n            seen.add(x)\n            result.append(x)\n    return result\n',
        'ai_template': 'def unique(lst):\n    """Remove duplicates from a list while preserving order.\n    \n    Args:\n        lst: Input list potentially containing duplicates\n    \n    Returns:\n        list: Deduplicated list with original order preserved\n    """\n    seen = set()\n    deduplicated = []\n    for item in lst:\n        if item not in seen:\n            seen.add(item)\n            deduplicated.append(item)\n    return deduplicated\n',
        'code_template': 'def unique(lst):\n    pass\n',
        'difficulty': 2, 'kp': [7, 10, 5],
    },
    {
        'title': '冒泡排序',
        'desc': '编写函数 bubble_sort(lst)，对列表进行冒泡排序（升序），直接修改原列表。',
        'func': 'bubble_sort',
        'test_cases': [
            {'input': '', 'call': 'lst=[3,1,4,1,5]; bubble_sort(lst); print(lst)', 'expected': '[1,1,3,4,5]'},
            {'input': '', 'call': 'lst=[1]; bubble_sort(lst); print(lst)', 'expected': '[1]'},
            {'input': '', 'call': 'lst=[5,4,3,2,1]; bubble_sort(lst); print(lst)', 'expected': '[1,2,3,4,5]'},
        ],
        'reference': 'def bubble_sort(lst):\n    n = len(lst)\n    for i in range(n):\n        for j in range(n - 1 - i):\n            if lst[j] > lst[j + 1]:\n                lst[j], lst[j + 1] = lst[j + 1], lst[j]\n',
        'ai_template': 'def bubble_sort(lst):\n    """Sort a list in ascending order using bubble sort algorithm.\n    \n    Args:\n        lst: List of comparable elements to be sorted in-place\n    """\n    n = len(lst)\n    for i in range(n):\n        swapped = False\n        for j in range(0, n - i - 1):\n            if lst[j] > lst[j + 1]:\n                lst[j], lst[j + 1] = lst[j + 1], lst[j]\n                swapped = True\n        if not swapped:\n            break\n',
        'code_template': 'def bubble_sort(lst):\n    pass\n',
        'difficulty': 3, 'kp': [5, 7, 4, 11],
    },
    {
        'title': '判断回文串',
        'desc': '编写函数 is_palindrome(s)，判断字符串是否为回文（正反读相同），忽略大小写。',
        'func': 'is_palindrome',
        'test_cases': [
            {'input': '', 'call': 'print(is_palindrome("racecar"))', 'expected': 'True'},
            {'input': '', 'call': 'print(is_palindrome("hello"))', 'expected': 'False'},
            {'input': '', 'call': 'print(is_palindrome("Aba"))', 'expected': 'True'},
        ],
        'reference': 'def is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\n',
        'ai_template': 'def is_palindrome(s):\n    """Check if a string is a palindrome (case-insensitive).\n    \n    Args:\n        s: Input string to check\n    \n    Returns:\n        bool: True if s is a palindrome, False otherwise\n    """\n    cleaned = s.lower()\n    left, right = 0, len(cleaned) - 1\n    while left < right:\n        if cleaned[left] != cleaned[right]:\n            return False\n        left += 1\n        right -= 1\n    return True\n',
        'code_template': 'def is_palindrome(s):\n    pass\n',
        'difficulty': 2, 'kp': [6, 3, 4, 11],
    },
    {
        'title': 'Student类定义',
        'desc': '编写Student类，包含__init__(self,name,score)方法，设置实例属性name和score，以及get_grade(self)方法：score>=90返回"A"，>=80返回"B"，>=60返回"C"，否则"D"。',
        'func': 'Student',
        'test_cases': [
            {'input': '', 'call': 's=Student("Tom",95); print(s.get_grade())', 'expected': 'A'},
            {'input': '', 'call': 's=Student("Jerry",75); print(s.get_grade())', 'expected': 'C'},
            {'input': '', 'call': 's=Student("Spike",60); print(s.get_grade())', 'expected': 'C'},
        ],
        'reference': 'class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\n    def get_grade(self):\n        if self.score >= 90:\n            return "A"\n        elif self.score >= 80:\n            return "B"\n        elif self.score >= 60:\n            return "C"\n        else:\n            return "D"\n',
        'ai_template': 'class Student:\n    """A class representing a student with a name and score.\n    \n    Attributes:\n        name: The student name\n        score: The student numerical score\n    """\n    def __init__(self, name: str, score: float) -> None:\n        self.name = name\n        self.score = score\n    \n    def get_grade(self) -> str:\n        """Calculate letter grade based on score.\n        \n        Returns:\n            Letter grade (A, B, C, or D)\n        """\n        if self.score >= 90:\n            return "A"\n        elif self.score >= 80:\n            return "B"\n        elif self.score >= 60:\n            return "C"\n        else:\n            return "D"\n',
        'code_template': 'class Student:\n    def __init__(self, name, score):\n        pass\n    def get_grade(self):\n        pass\n',
        'difficulty': 3, 'kp': [15, 4, 11],
    },
    {
        'title': '矩形类继承',
        'desc': '编写Rectangle类（__init__(self,width,height)）和Square类（继承Rectangle），Square的__init__只接收一个参数side。两个类都有area()方法返回面积。',
        'func': 'Square',
        'test_cases': [
            {'input': '', 'call': 'r=Rectangle(3,4); print(r.area())', 'expected': '12'},
            {'input': '', 'call': 's=Square(5); print(s.area())', 'expected': '25'},
            {'input': '', 'call': 'print(isinstance(Square(2), Rectangle))', 'expected': 'True'},
        ],
        'reference': 'class Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n    def area(self):\n        return self.width * self.height\n\nclass Square(Rectangle):\n    def __init__(self, side):\n        super().__init__(side, side)\n',
        'ai_template': 'class Rectangle:\n    """A rectangle shape with width and height."""\n    def __init__(self, width: float, height: float) -> None:\n        self.width = width\n        self.height = height\n    \n    def area(self) -> float:\n        """Calculate the area of the rectangle."""\n        return self.width * self.height\n\n\nclass Square(Rectangle):\n    """A square shape, which is a special case of a rectangle."""\n    def __init__(self, side: float) -> None:\n        super().__init__(side, side)\n',
        'code_template': 'class Rectangle:\n    def __init__(self, width, height):\n        pass\n    def area(self):\n        pass\n\nclass Square(Rectangle):\n    def __init__(self, side):\n        pass\n',
        'difficulty': 4, 'kp': [15, 16, 13],
    },
    {
        'title': '合并两个有序列表',
        'desc': '编写函数 merge_sorted_lists(a, b)，合并两个已升序排列的列表，返回一个新的升序列表。',
        'func': 'merge_sorted_lists',
        'test_cases': [
            {'input': '', 'call': 'print(merge_sorted_lists([1,3,5], [2,4,6]))', 'expected': '[1,2,3,4,5,6]'},
            {'input': '', 'call': 'print(merge_sorted_lists([1,2], []))', 'expected': '[1,2]'},
            {'input': '', 'call': 'print(merge_sorted_lists([], [3,4]))', 'expected': '[3,4]'},
        ],
        'reference': 'def merge_sorted_lists(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result\n',
        'ai_template': 'def merge_sorted_lists(a, b):\n    """Merge two sorted lists into one sorted list.\n    \n    Args:\n        a: First sorted list (ascending)\n        b: Second sorted list (ascending)\n    \n    Returns:\n        A new sorted list containing all elements from a and b\n    """\n    merged = []\n    i, j = 0, 0\n    while i < len(a) and j < len(b):\n        if a[i] < b[j]:\n            merged.append(a[i])\n            i += 1\n        else:\n            merged.append(b[j])\n            j += 1\n    if i < len(a):\n        merged.extend(a[i:])\n    if j < len(b):\n        merged.extend(b[j:])\n    return merged\n',
        'code_template': 'def merge_sorted_lists(a, b):\n    pass\n',
        'difficulty': 3, 'kp': [5, 7, 4, 11],
    },
    {
        'title': '杨辉三角',
        'desc': '编写函数 pascal_triangle(n)，返回杨辉三角的前n行（n>=1），每行为一个列表。',
        'func': 'pascal_triangle',
        'test_cases': [
            {'input': '', 'call': 'print(pascal_triangle(3))', 'expected': '[[1],[1,1],[1,2,1]]'},
            {'input': '', 'call': 'print(pascal_triangle(1))', 'expected': '[[1]]'},
            {'input': '', 'call': 'print(pascal_triangle(5))', 'expected': '[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]'},
        ],
        'reference': 'def pascal_triangle(n):\n    result = [[1]]\n    for i in range(1, n):\n        prev = result[-1]\n        row = [1]\n        for j in range(len(prev) - 1):\n            row.append(prev[j] + prev[j + 1])\n        row.append(1)\n        result.append(row)\n    return result\n',
        'ai_template': 'def pascal_triangle(n):\n    """Generate Pascals triangle up to n rows.\n    \n    Args:\n        n: Number of rows to generate\n    \n    Returns:\n        List of lists representing Pascals triangle rows\n    """\n    output = [[1]]\n    for row_idx in range(1, n):\n        previous_row = output[-1]\n        new_row = [1]\n        for col_idx in range(len(previous_row) - 1):\n            new_row.append(previous_row[col_idx] + previous_row[col_idx + 1])\n        new_row.append(1)\n        output.append(new_row)\n    return output\n',
        'code_template': 'def pascal_triangle(n):\n    pass\n',
        'difficulty': 3, 'kp': [5, 7, 9, 11],
    },
    {
        'title': '二分查找',
        'desc': '编写函数 binary_search(sorted_lst, target)，在有序列表中二分查找目标值，返回索引，未找到返回-1。',
        'func': 'binary_search',
        'test_cases': [
            {'input': '', 'call': 'print(binary_search([1,3,5,7,9], 5))', 'expected': '2'},
            {'input': '', 'call': 'print(binary_search([1,3,5,7,9], 2))', 'expected': '-1'},
            {'input': '', 'call': 'print(binary_search([1], 1))', 'expected': '0'},
        ],
        'reference': 'def binary_search(sorted_lst, target):\n    lo, hi = 0, len(sorted_lst) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if sorted_lst[mid] == target:\n            return mid\n        elif sorted_lst[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n',
        'ai_template': 'def binary_search(sorted_lst, target):\n    """Perform binary search on a sorted list.\n    \n    Args:\n        sorted_lst: A sorted list of comparable elements\n        target: The element to search for\n    \n    Returns:\n        int: Index of target if found, -1 otherwise\n    """\n    left, right = 0, len(sorted_lst) - 1\n    while left <= right:\n        middle = left + (right - left) // 2\n        if sorted_lst[middle] == target:\n            return middle\n        elif sorted_lst[middle] < target:\n            left = middle + 1\n        else:\n            right = middle - 1\n    return -1\n',
        'code_template': 'def binary_search(sorted_lst, target):\n    pass\n',
        'difficulty': 3, 'kp': [5, 4, 7, 11],
    },
    {
        'title': '异常处理安全除法',
        'desc': '编写函数 safe_divide(a, b)，返回a/b的结果。如果除数为0或发生任何异常，返回None。',
        'func': 'safe_divide',
        'test_cases': [
            {'input': '', 'call': 'print(safe_divide(10, 2))', 'expected': '5.0'},
            {'input': '', 'call': 'print(safe_divide(5, 0))', 'expected': 'None'},
            {'input': '', 'call': 'print(safe_divide(3, 4))', 'expected': '0.75'},
        ],
        'reference': 'def safe_divide(a, b):\n    try:\n        return a / b\n    except Exception:\n        return None\n',
        'ai_template': 'def safe_divide(a, b):\n    """Safely divide two numbers with error handling.\n    \n    Args:\n        a: The numerator\n        b: The denominator\n    \n    Returns:\n        float: Result of a/b, or None if division fails\n    """\n    try:\n        result = a / b\n        return result\n    except ZeroDivisionError:\n        return None\n    except TypeError:\n        return None\n',
        'code_template': 'def safe_divide(a, b):\n    pass\n',
        'difficulty': 2, 'kp': [18, 3, 11, 13],
    },
    {
        'title': '字典合并',
        'desc': '编写函数 merge_dicts(d1, d2)，合并两个字典。键冲突时，值较大的保留。',
        'func': 'merge_dicts',
        'test_cases': [
            {'input': '', 'call': 'print(merge_dicts({"a":1,"b":2}, {"b":3,"c":4}))', 'expected': "{'a':1,'b':3,'c':4}"},
            {'input': '', 'call': 'print(merge_dicts({}, {"x":5}))', 'expected': "{'x':5}"},
            {'input': '', 'call': 'print(merge_dicts({"k":10}, {"k":5}))', 'expected': "{'k':10}"},
        ],
        'reference': 'def merge_dicts(d1, d2):\n    result = d1.copy()\n    for k, v in d2.items():\n        if k in result:\n            result[k] = max(result[k], v)\n        else:\n            result[k] = v\n    return result\n',
        'ai_template': 'def merge_dicts(d1, d2):\n    """Merge two dictionaries, keeping the larger value on key conflict.\n    \n    Args:\n        d1: First dictionary\n        d2: Second dictionary\n    \n    Returns:\n        dict: Merged dictionary\n    """\n    merged = d1.copy()\n    for key, value in d2.items():\n        if key in merged:\n            merged[key] = max(merged[key], value)\n        else:\n            merged[key] = value\n    return merged\n',
        'code_template': 'def merge_dicts(d1, d2):\n    pass\n',
        'difficulty': 2, 'kp': [9, 5, 3, 11],
    },
    {
        'title': '列表推导式过滤',
        'desc': '编写函数 filter_even_squares(lst)，使用列表推导式返回列表中所有偶数的平方。',
        'func': 'filter_even_squares',
        'test_cases': [
            {'input': '', 'call': 'print(filter_even_squares([1,2,3,4,5]))', 'expected': '[4,16]'},
            {'input': '', 'call': 'print(filter_even_squares([1,3,5]))', 'expected': '[]'},
            {'input': '', 'call': 'print(filter_even_squares([0,2,4]))', 'expected': '[0,4,16]'},
        ],
        'reference': 'def filter_even_squares(lst):\n    return [x*x for x in lst if x % 2 == 0]\n',
        'ai_template': 'def filter_even_squares(lst):\n    """Filter and square even numbers using list comprehension.\n    \n    Args:\n        lst: List of integers\n    \n    Returns:\n        list: Squares of even numbers in the input\n    """\n    return [x ** 2 for x in lst if x % 2 == 0]\n',
        'code_template': 'def filter_even_squares(lst):\n    pass\n',
        'difficulty': 2, 'kp': [20, 7, 3],
    },
]

def seed_knowledge_graph():
    if count("SELECT COUNT(*) FROM knowledge_points") > 0:
        return
    for kp_id, name, desc, full_desc, cat in KNOWLEDGE_POINTS:
        insert("INSERT INTO knowledge_points (id, name, description, category) VALUES (?,?,?,?)",
               (kp_id, name, f'{desc}; {full_desc}', cat))
    for from_id, to_id in KNOWLEDGE_EDGES:
        insert("INSERT OR IGNORE INTO knowledge_edges (from_kp_id, to_kp_id) VALUES (?,?)",
               (from_id, to_id))

def seed_questions():
    if count("SELECT COUNT(*) FROM questions") > 0:
        return

    for title, opts, answer, diff, kps in SINGLE_CHOICE_QUESTIONS:
        insert("INSERT INTO questions (type, title, options, correct_answer, difficulty, knowledge_points) VALUES (?,?,?,?,?,?)",
               ('single_choice', title, opts, answer, diff, json.dumps(kps)))

    for title, opts, answer, diff, kps in MULTI_CHOICE_QUESTIONS:
        insert("INSERT INTO questions (type, title, options, correct_answer, difficulty, knowledge_points) VALUES (?,?,?,?,?,?)",
               ('multi_choice', title, opts, answer, diff, json.dumps(kps)))

    for title, answer, diff, kps in TRUE_FALSE_QUESTIONS:
        insert("INSERT INTO questions (type, title, options, correct_answer, difficulty, knowledge_points) VALUES (?,?,?,?,?,?)",
               ('true_false', title, None, answer, diff, json.dumps(kps)))

    for title, answer, standard, aliases, diff, kps in FILL_BLANK_QUESTIONS:
        aliases_full = list(set(standard + aliases))
        insert("INSERT INTO questions (type, title, options, correct_answer, difficulty, knowledge_points, aliases) VALUES (?,?,?,?,?,?,?)",
               ('fill_blank', title, None, answer, diff, json.dumps(kps), json.dumps(aliases_full, ensure_ascii=False)))

    for pq in PROGRAMMING_QUESTIONS:
        insert("INSERT INTO questions (type, title, options, correct_answer, difficulty, knowledge_points, test_cases, code_template, ai_code_template, reference_code) VALUES (?,?,?,?,?,?,?,?,?,?)",
               ('programming', f"{pq['title']}: {pq['desc']}", None, pq['func'],
                pq['difficulty'], json.dumps(pq['kp']),
                json.dumps(pq['test_cases'], ensure_ascii=False),
                pq['code_template'], pq['ai_template'], pq['reference']))

def seed_users():
    if count("SELECT COUNT(*) FROM users") > 0:
        return
    from werkzeug.security import generate_password_hash
    pwd = generate_password_hash('123456', method='pbkdf2:sha256:600000')

    insert("INSERT INTO users (username, password_hash, role, display_name, linked_user_id) VALUES (?,?,?,?,?)",
           ('guozicheng_teacher', pwd, 'teacher', '郭子成(教师)', None))
    tid = count("SELECT COUNT(*) FROM users")

    insert("INSERT INTO users (username, password_hash, role, display_name, linked_user_id) VALUES (?,?,?,?,?)",
           ('guozicheng_student', pwd, 'student', '郭子成(学生)', tid))
    sid = count("SELECT COUNT(*) FROM users")

    insert("UPDATE users SET linked_user_id=? WHERE id=?", (sid, tid))

    for i in range(1, 21):
        insert("INSERT INTO users (username, password_hash, role, display_name) VALUES (?,?,?,?)",
               (f'stu_{i:03d}', pwd, 'student', f'模拟学生{i:02d}'))

def run_seed():
    seed_knowledge_graph()
    seed_questions()
    seed_users()
    print("Seed data loaded successfully!")
    print(f"Knowledge points: {count('SELECT COUNT(*) FROM knowledge_points')}")
    print(f"Questions: {count('SELECT COUNT(*) FROM questions')}")
    print(f"Users: {count('SELECT COUNT(*) FROM users')}")
